Repository cse110-sp23-group4/cse110-sp23-group4, pull requests merged in 2023-04, with the labels that each got.

#8 create new branch and update pictures
  admin/.DS_Store
  admin/team.md
  admin/teamheadshots/abjitheadshot.jpeg
  admin/teamheadshots/christianheadshot.png
Labels: Organization

#13 Basic text to speech capabilities added
  source/8-ball/script.js
Labels: Backend

#16 add meeting notes, changes to spec, 8-ball bckgrnd
  admin/meetings/042323-8-ball-progress.md
  source/8-ball/assets/8-ball-background.jpg
  specs/8-ball/8-ball_spec.md
Labels: documentation, Organization, Design

#18 added background img to 8-ball site
  source/8-ball/index.html
  source/8-ball/script.js
  source/8-ball/style.css
Labels: Frontend, Design

#25 8 ball redesign
  source/8-ball/assets/fire.gif
  source/8-ball/index.html
  source/8-ball/script.js
  source/8-ball/style.css
Labels: Frontend, Design

#26 updated css and added title
  source/8-ball/index.html
  source/8-ball/style.css
Labels: Frontend, Design

#30 added presentation.md and script.md
  specs/8-ball/presentation.md
  specs/8-ball/script.md
Labels: documentation

#50 made css changes to input box and fonts
  source/8-ball/index.html
  source/8-ball/style.css
Labels: Frontend, Design

#53 spacing and font changes
  source/8-ball/index.html
  source/8-ball/style.css
Labels: Frontend, Design

#58 Update style.css
  source/8-ball/style.css
Labels: Frontend, Design

#61 Added documentation for typeResponse()
  specs/8-ball/docs.md
Labels: documentation
