Repository cse110-sp23-group4/cse110-sp23-group4, pull requests merged in 2023-05, with the labels that each got.

#73 Nnandhakumar user docs
  specs/users/assets/Feature-1.jpg
  specs/users/assets/Feature-2.jpg
  specs/users/nnandhakumar_user_docs.md
Labels: Design

#75 adrs 1 and 2
  specs/adrs/1-fortune-telling-format.md
  specs/adrs/2-no-inputting-questions.md
  specs/adrs/ADR-TEMPLATE.md
Labels: documentation

#76 Create samuel_user-docs.md
  specs/users/samuel_user-docs.md
Labels: documentation

#77 Pitch draft check in
  README.md
  specs/.DS_Store
  specs/pitch/assets/first-itr-flowchart.png
  specs/pitch/assets/first-itr-fortune-backend.png
  specs/pitch/assets/first-itr-full-wireframe.png
  specs/pitch/assets/fortune-bank-wireframe.png
  specs/pitch/assets/fortune-pick-wireframe.png
  specs/pitch/assets/landing-page-wireframe.png
  specs/pitch/assets/pick-category-wireframe.png
  specs/pitch/pitch.md
  specs/pitch/pitch.pdf
Labels: documentation

#97 Add jsdocs style guide to repo
  specs/fortune-telling-docs/jsdocs-style-guide.md
Labels: documentation

#99 Add coding style and file naming ADRs
  specs/adrs/4-team-coding-style.md
  specs/adrs/5-file-naming-style.md
Labels: documentation

#101 Basic layout and design for landing page
  source/prototyping/landing-prototype.html
  source/prototyping/landing-style.css
Labels: frontend, design

#111 Fortune prediction
  source/prototyping/card-prototype.html
  source/prototyping/card-script.js
  source/prototyping/menu-script.js
Labels: backend

#118 Basic design
  source/prototyping/assets/card-page/backdrop.png
  source/prototyping/assets/card-page/disastrous.png
  source/prototyping/assets/card-page/hopeful.png
  source/prototyping/assets/card-page/neutral.png
  source/prototyping/assets/card-page/optimistic.png
  source/prototyping/assets/card-page/pessimistic.png
  source/prototyping/assets/card-page/table.png
  source/prototyping/assets/card-page/unknown.png
  source/prototyping/assets/landing-page/backdrop.png
  source/prototyping/assets/menu-page/Panel.js
  source/prototyping/assets/menu-page/backdrop.png
  source/prototyping/assets/menu-page/wood-plank.jpg
  source/prototyping/assets/menu-page/wood-plank.png
  source/prototyping/card-prototype.html
  source/prototyping/card-script.js
  source/prototyping/card-style.css
  source/prototyping/landing-prototype.html
  source/prototyping/landing-style.css
  source/prototyping/menu-prototype.html
  source/prototyping/menu-script.js
  source/prototyping/menu-style.css
Labels: design

#119 Fortune Bank
  .vscode/settings.json
  source/prototyping/saved-readings-prototype.html
  source/prototyping/saved-readings-script.js
  source/prototyping/saved-readings-style.css
Labels: backend

#120 Sprint 2 Landing Page Styling First Draft Complete
  source/prototyping/assets/fonts/AbrilFatface-Regular.ttf
  source/prototyping/assets/fonts/PlayfairDisplaySC-Black.ttf
  source/prototyping/assets/fonts/PlayfairDisplaySC-BlackItalic.ttf
  source/prototyping/assets/fonts/PlayfairDisplaySC-Bold.ttf
  source/prototyping/assets/fonts/PlayfairDisplaySC-Regular.ttf
  source/prototyping/landing-prototype.html
  source/prototyping/landing-style.css
Labels: frontend, design

#125 created styling for saved readings page
  source/prototyping/assets/saved-readings-page/saved-readings-page-background.jpeg
  source/prototyping/saved-readings-style.css
Labels: frontend

#133 Add source\node_modules to .gitignore
  .gitignore
Labels: testing, small change

#136 Integrate fortune responses
  source/prototyping/assets/card-page/library_card_wiki_design.png
  source/prototyping/assets/fortunes/fortunes.json
  source/prototyping/card-prototype.html
  source/prototyping/card-script.js
Labels: bug, enhancement, backend

#137 Add landing page tests
  source/__tests__/landing-page-test.js
Labels: testing
