Repository cse110-sp23-group4/cse110-sp23-group4, pull requests merged in 2023-06, with the labels that each got.

#148 Add github action for unit tests and e2e testing
  .github/workflows/testing.yml
  .gitignore
  jest-puppeteer.config.js
  package-lock.json
  package.json
  source/__tests__/landing-page-test.js
Labels: testing

#160 Change menu page category buttons
  source/prototyping/assets/menu-page/wood-placard-vertical.png
  source/prototyping/assets/menu-page/wood-plank.jpg
  source/prototyping/assets/menu-page/wood-plank.png
  source/prototyping/menu-script.js
  source/prototyping/menu-style.css
Labels: frontend

#151 Landing hut zooming
  .gitignore
  source/prototyping/landing-prototype.html
  source/prototyping/landing-script.js
  source/prototyping/landing-style.css
  source/prototyping/menu-script.js
Labels: frontend

#162 Add JSDoc automation
  .github/workflows/docs.yml
  .gitignore
  README.md
  jsdoc.config.json
  specs/fortune-telling-docs/card-script.js.html
  specs/fortune-telling-docs/fonts/OpenSans-Bold-webfont.eot
  specs/fortune-telling-docs/fonts/OpenSans-Bold-webfont.svg
  specs/fortune-telling-docs/fonts/OpenSans-Bold-webfont.woff
  specs/fortune-telling-docs/fonts/OpenSans-BoldItalic-webfont.eot
  specs/fortune-telling-docs/fonts/OpenSans-BoldItalic-webfont.svg
  specs/fortune-telling-docs/fonts/OpenSans-BoldItalic-webfont.woff
  specs/fortune-telling-docs/fonts/OpenSans-Italic-webfont.eot
  specs/fortune-telling-docs/fonts/OpenSans-Italic-webfont.svg
  specs/fortune-telling-docs/fonts/OpenSans-Italic-webfont.woff
  specs/fortune-telling-docs/fonts/OpenSans-Light-webfont.eot
  specs/fortune-telling-docs/fonts/OpenSans-Light-webfont.svg
  specs/fortune-telling-docs/fonts/OpenSans-Light-webfont.woff
  specs/fortune-telling-docs/fonts/OpenSans-LightItalic-webfont.eot
  specs/fortune-telling-docs/fonts/OpenSans-LightItalic-webfont.svg
  specs/fortune-telling-docs/fonts/OpenSans-LightItalic-webfont.woff
  specs/fortune-telling-docs/fonts/OpenSans-Regular-webfont.eot
  specs/fortune-telling-docs/fonts/OpenSans-Regular-webfont.svg
  specs/fortune-telling-docs/fonts/OpenSans-Regular-webfont.woff
  specs/fortune-telling-docs/global.html
  specs/fortune-telling-docs/index.html
  specs/fortune-telling-docs/landing-script.js.html
  specs/fortune-telling-docs/menu-script.js.html
  specs/fortune-telling-docs/saved-readings-script.js.html
  specs/fortune-telling-docs/scripts/linenumber.js
  specs/fortune-telling-docs/scripts/prettify/Apache-License-2.0.txt
  specs/fortune-telling-docs/scripts/prettify/lang-css.js
  specs/fortune-telling-docs/scripts/prettify/prettify.js
  specs/fortune-telling-docs/styles/jsdoc-default.css
  specs/fortune-telling-docs/styles/prettify-jsdoc.css
  specs/fortune-telling-docs/styles/prettify-tomorrow.css
Labels: documentation

#165 Landing page e2e tests
  source/__tests__/landing-page-test.js
  specs/fortune-telling-docs/card-script.js.html
  specs/fortune-telling-docs/global.html
  specs/fortune-telling-docs/index.html
  specs/fortune-telling-docs/landing-script.js.html
  specs/fortune-telling-docs/menu-script.js.html
  specs/fortune-telling-docs/saved-readings-script.js.html
Labels: testing

#167 Saved readings e2e tests
  source/__tests__/cards-page-test.js
  source/__tests__/menu-page-test.js
  source/__tests__/saved-readings-test.js
Labels: testing

#164 Delete individual fortune
  source/prototyping/card-prototype.html
  source/prototyping/card-script.js
  source/prototyping/card-style.css
  source/prototyping/saved-readings-prototype.html
  source/prototyping/saved-readings-script.js
  source/prototyping/saved-readings-style.css
  specs/fortune-telling-docs/card-script.js.html
  specs/fortune-telling-docs/global.html
  specs/fortune-telling-docs/index.html
  specs/fortune-telling-docs/landing-script.js.html
  specs/fortune-telling-docs/menu-script.js.html
  specs/fortune-telling-docs/saved-readings-script.js.html
Labels: backend

#171 Card e2e tests
  .gitignore
  source/__tests__/card-page-test.js
  source/prototyping/card-script.js
  source/prototyping/saved-readings-script.js
  specs/fortune-telling-docs/card-script.js.html
  specs/fortune-telling-docs/global.html
  specs/fortune-telling-docs/index.html
  specs/fortune-telling-docs/landing-script.js.html
  specs/fortune-telling-docs/menu-script.js.html
  specs/fortune-telling-docs/saved-readings-script.js.html
Labels: bug, backend

#172 Prevent duplicate
  source/prototyping/saved-readings-prototype.html
  source/prototyping/saved-readings-script.js
  specs/fortune-telling-docs/card-script.js.html
  specs/fortune-telling-docs/global.html
  specs/fortune-telling-docs/index.html
  specs/fortune-telling-docs/landing-script.js.html
  specs/fortune-telling-docs/menu-script.js.html
  specs/fortune-telling-docs/saved-readings-script.js.html
Labels: bug, backend, design

#173 Fixed test to check menu page category button functionality
  source/__tests__/menu-page-test.js
  specs/fortune-telling-docs/card-script.js.html
  specs/fortune-telling-docs/global.html
  specs/fortune-telling-docs/index.html
  specs/fortune-telling-docs/landing-script.js.html
  specs/fortune-telling-docs/menu-script.js.html
  specs/fortune-telling-docs/saved-readings-script.js.html
Labels: testing

#174 Add/Modify some file headers
  source/prototyping/landing-script.js
  source/prototyping/saved-readings-script.js
  specs/fortune-telling-docs/card-script.js.html
  specs/fortune-telling-docs/global.html
  specs/fortune-telling-docs/index.html
  specs/fortune-telling-docs/landing-script.js.html
  specs/fortune-telling-docs/menu-script.js.html
  specs/fortune-telling-docs/saved-readings-script.js.html
Labels: documentation, small change

#177 Fix duplicate fortune
  source/prototyping/saved-readings-prototype.html
  source/prototyping/saved-readings-script.js
  source/prototyping/saved-readings-style.css
Labels: bug, backend

#166 Woosh cards
  source/prototyping/card-prototype.html
  source/prototyping/card-script.js
  source/prototyping/card-style.css
  specs/fortune-telling-docs/card-script.js.html
  specs/fortune-telling-docs/global.html
Labels: frontend

#194 Fortune page e2e tests
  source/__tests__/card-page-test.js
  source/__tests__/cards-page-test.js
  source/__tests__/landing-page-test.js
  source/__tests__/menu-page-test.js
  source/fortune-telling/card-script.js
Labels: testing

#202 Fortune generation logic
  source/fortune-telling/card-script.js
  source/fortune-telling/card.html
Labels: bug, documentation, enhancement, help wanted, organization, backend

#207 Predict reset bugfix
  source/fortune-telling/card-script.js
Labels: bug, enhancement, backend

#209 Fortune page e2e tests
  source/__tests__/card-page-test.js
Labels: testing, small change

#210 Saved readings e2e tests
  source/__tests__/saved-readings-page-test.js
  source/__tests__/saved-readings-test.js
Labels: testing

#211 Fixed Landing Page Zoom Animation
  source/fortune-telling/landing-script.js
  source/fortune-telling/landing-style.css
Labels: bug, frontend

#200 Web design rework
  source/fortune-telling/assets/card-page/black.png
  source/fortune-telling/assets/card-page/life_back.png
  source/fortune-telling/assets/card-page/love_back.png
  source/fortune-telling/assets/card-page/school_back.png
  source/fortune-telling/card-script.js
  source/fortune-telling/card.html
  source/fortune-telling/menu-style.css
  source/fortune-telling/saved-readings-script.js
Labels: frontend, design

#222 updated favicon for all pages
  source/fortune-telling/card.html
  source/fortune-telling/landing.html
  source/fortune-telling/menu.html
  source/fortune-telling/saved.html
Labels: frontend, design, small change

#220 Edit saved-reading test
  source/__tests__/saved-readings-page-test.js
Labels: small change

#223 Test hotfix
  source/__tests__/card-page-test.js
  source/__tests__/saved-readings-page-test.js
Labels: testing, small change

#225 Fixed Card Still selected on Reset Bug
  source/fortune-telling/card-script.js
Labels: bug, small change

#226 Font overhaul
  source/fortune-telling/card-style.css
  source/fortune-telling/card.html
  source/fortune-telling/landing-style.css
  source/fortune-telling/menu-style.css
  source/fortune-telling/saved-readings-style.css
  source/fortune-telling/saved.html
Labels: frontend

#229 increase length of test
  source/__tests__/saved-readings-page-test.js
Labels: testing, small change

#232 fixed pathing issues
  source/__tests__/card-page-test.js
  source/__tests__/landing-page-test.js
  source/__tests__/menu-page-test.js
  source/__tests__/saved-readings-page-test.js
  source/fortune-telling/assets/card-page/card-sparkle.mp3
  source/fortune-telling/assets/favicon.ico
  source/fortune-telling/card-script.js
  source/fortune-telling/card.html
  source/fortune-telling/landing-script.js
  source/fortune-telling/landing.html
  source/fortune-telling/menu-script.js
  source/fortune-telling/menu.html
  source/fortune-telling/saved-readings-script.js
  source/fortune-telling/saved-readings-style.css
  source/fortune-telling/saved.html
Labels: enhancement
